services:
  nginx:
    image: nginx:latest
    container_name: nginx-lesson01
    ports:
      - "60001:80"
    volumes:
      # nginxの大元の設定. この設定ファイルから別の設定ファイルがincludeされていく.
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf

      # バーチャルホスト毎の設定
      - ./etc/nginx/conf.d:/etc/nginx/conf.d

      #### WEBサーバーでの公開ファイル ####
      - ./var/www:/var/www
